Everything in ``lasio`` is available from a basic import, so all you need to do is:

In [1]:
import lasio

The ``read()`` function accepts a filename, string, URL, or file-like object

In [2]:
import os

l = lasio.read(os.path.join("..", "tests", "examples", "6038187_v1.2_short.las"))

it returns a ``LASFile`` object

In [3]:
type(l)

lasio.las.LASFile

Curves are available as [numpy](http://www.numpy.org/) 1D arrays

In [4]:
l.keys()

['DEPT', 'CALI', 'DFAR', 'DNEAR', 'GAMN', 'NEUT', 'PR', 'SP', 'COND']

so to see the NEUT data use:

In [5]:
l['NEUT']

array([ 1152.01 ,  1233.99 ,  1212.   ,  1161.01 ,  1080.02 ,  1188.98 ,
        1164.   ,  1169.   ,  1202.   ,  1168.01 ,  1179.   ,  1146.   ,
        1169.   ,  1182.   ,  1156.01 ,  1154.   ,  1142.   ,  1146.   ,
        1171.   ,  1119.01 ,  1070.01 ,  1150.99 ,  1256.98 ,  1291.   ,
        1301.   ,  1371.99 ,  1358.   ,  1368.   ,  1482.99 ,  1423.01 ,
        1350.01 ,  1156.02 ,  1013.03 ,   876.016,   798.016,   629.026,
         618.001,   659.992,   689.997,   765.984,   753.002,   741.001,
         734.001,   767.996,   730.008,   747.997,   762.999,   793.994,
         776.002,   854.983,   827.004,   886.994,   869.003,   863.001,
         869.999,   884.998,   919.997,   879.008,   909.996,   931.995,
         954.996,   986.997,   970.003,   953.002,   925.006,   899.004,
         952.995,   967.997,   926.005,   924.   ,   936.998,   968.997,
         922.009,   934.999,   931.001,   945.998,   913.003,   903.002,
         964.993,   937.006,   925.002,   909.001, 

You can also access curves by index (remembering that the first index is zero but the first curve is the reference curve, usually depth.

So for example the first data curve in this file is CALI:

In [6]:
l['CALI']

array([ 101.78 ,  101.738,  101.738,  101.858,  101.798,  101.756,
        101.804,  101.798,  101.852,  101.87 ,  101.906,  101.816,
        101.714,  101.768,  101.816,  101.828,  101.696,  101.69 ,
        101.744,  101.66 ,  101.6  ,  101.708,  101.78 ,  101.792,
        101.618,  101.576,  101.606,  101.504,  101.516,  101.54 ,
        101.546,  101.45 ,  101.612,  101.744,  101.762,  101.762,
        101.792,  101.816,  101.696,  101.696,  101.666,  101.69 ,
        101.858,  101.81 ,  101.792,  101.828,  101.81 ,  101.54 ,
        101.54 ,  101.516,  101.516,  101.498,  101.504,  101.54 ,
        101.348,  101.366,  101.42 ,  101.408,  101.36 ,  101.318,
        101.324,  101.348,  101.307,  101.283,  101.378,  101.295,
        101.283,  101.396,  101.36 ,  101.372,  101.348,  101.408,
        101.402,  101.498,  101.432,  101.516,  101.594,  101.528,
        101.534,  101.528,  101.528,  101.528,  101.66 ,  101.732,
        101.696,  101.714,  101.696,  101.66 ,  101.666,  101.

which is the same as using the index 1:

In [7]:
l[1]

array([ 101.78 ,  101.738,  101.738,  101.858,  101.798,  101.756,
        101.804,  101.798,  101.852,  101.87 ,  101.906,  101.816,
        101.714,  101.768,  101.816,  101.828,  101.696,  101.69 ,
        101.744,  101.66 ,  101.6  ,  101.708,  101.78 ,  101.792,
        101.618,  101.576,  101.606,  101.504,  101.516,  101.54 ,
        101.546,  101.45 ,  101.612,  101.744,  101.762,  101.762,
        101.792,  101.816,  101.696,  101.696,  101.666,  101.69 ,
        101.858,  101.81 ,  101.792,  101.828,  101.81 ,  101.54 ,
        101.54 ,  101.516,  101.516,  101.498,  101.504,  101.54 ,
        101.348,  101.366,  101.42 ,  101.408,  101.36 ,  101.318,
        101.324,  101.348,  101.307,  101.283,  101.378,  101.295,
        101.283,  101.396,  101.36 ,  101.372,  101.348,  101.408,
        101.402,  101.498,  101.432,  101.516,  101.594,  101.528,
        101.534,  101.528,  101.528,  101.528,  101.66 ,  101.732,
        101.696,  101.714,  101.696,  101.66 ,  101.666,  101.

All the curves are stored as a two-dimensional ``ndarray`` under the ``data`` attribute:

In [8]:
type(l.data)

numpy.ndarray

In [9]:
l.data.shape

(121, 9)

In [10]:
l.data

array([[  1.20000000e+01,   1.01780000e+02,   8.83000000e-01, ...,
          5.04999000e+04,   1.00592000e+02,   8.22680000e+02],
       [  1.20500000e+01,   1.01738000e+02,   8.83000000e-01, ...,
          5.04999000e+04,   1.00510000e+02,   8.10824000e+02],
       [  1.21000000e+01,   1.01738000e+02,   8.73000000e-01, ...,
          5.04999000e+04,   1.00580000e+02,   8.01439000e+02],
       ..., 
       [  1.79000000e+01,   1.01241000e+02,   1.41700000e+00, ...,
          5.04999000e+04,   1.00537000e+02,   6.88347000e+01],
       [  1.79500000e+01,   1.01235000e+02,   1.37800000e+00, ...,
          5.04999000e+04,   1.00558000e+02,   6.93289000e+01],
       [  1.80000000e+01,   1.01259000e+02,   1.38100000e+00, ...,
          5.04999000e+04,   1.00562000e+02,   6.53776000e+01]])

You can always see the text of the original LAS file loaded here:

In [11]:
type(l._text)

str

In [12]:
len(l._text)

15307

In [13]:
print(l._text)

#------------------------------------------------------------
~VERSION INFORMATION
VERS.               2.0  :CWLS LOG ASCII STANDARD - VERSION 2.0
WRAP.                NO  :ONE LINE PER DEPTH STEP
#------------------------------------------------------------
~WELL INFORMATION
STRT.M        0.0500000  :FIRST INDEX VALUE
STOP.M          136.600  :LAST INDEX VALUE
STEP.M        0.0500000  :STEP
NULL.            -99999  :NULL VALUE
COMP.                    :COMP
WELL.        Scorpio E1  :WELL
FLD.                     :
LOC.             Mt Eba  :LOC
SRVC.                    :
CTRY.                    :
STAT.                SA  :STAT
CNTY.                    :
DATE.        15/03/2015  :DATE
UWI.           6038-187  :WUNT
#------------------------------------------------------------
~CURVE INFORMATION
DEPT.M                   :DEPTH
CALI.MM                  :CALI
DFAR.G/CM3               :DFAR
DNEAR.G/CM3              :DNEAR
GAMN.GAPI                :GAMN
NEUT.CPS                 :NEUT
PR.OHM